### ISSUE TITLE
알고리즘 + 깃헙 공부하기 참여하실분 구합니다

### ISSUE THREAD

**Issue by dongjji** [dongjji/Algorithm#1]
참여하실 분 구합니다.

**Comment by dongjji** [comment]
저는 자바스크립트로 알고리즘 공부를 할 예정입니다 이슈는 자유롭게 달아주세요!

**Comment by Ernstjunger-1914** [comment]
어떻게 참가하면 되는지 좀 더 상세히 설명해주실 수 있을까요?

**Comment by dongjji** [comment]
@Ernstjunger-1914 
네 가능합니다. 
카테고리별  디렉토리 새로 생성하신 다음에 공부한 내용을 fork한 레포에 
커밋하시고 PR보내주시면 됩니다!
아직 초기 단계라서 기여 방법도 자주 변경하고 있습니다!
기여하시는 분들과 잘 조율해서 같이 가꿔나가는 방향으로 하고 있어요!
관심 가져주셔서 감사합니다~

**Comment by Ernstjunger-1914** [comment]
> @Ernstjunger-1914 네 가능합니다. 카테고리별 디렉토리 새로 생성하신 다음에 공부한 내용을 fork한 레포에 커밋하시고 PR보내주시면 됩니다! 아직 초기 단계라서 기여 방법도 자주 변경하고 있습니다! 기여하시는 분들과 잘 조율해서 같이 가꿔나가는 방향으로 하고 있어요! 관심 가져주셔서 감사합니다~

추가로 참여자는 본인 이름으로 브랜치 하나 파서 진행하면 되나요?

**Comment by dongjji** [comment]
@Ernstjunger-1914 
https://github.com/dongjji/Algorithm/blob/master/CONTRIBUTING.md
기여가이드에 참고하시고 질문 있으시면 issue 새롭게 달아주세요
